### ISSUE TITLE
Join adds unnecessary commas and spaces, in Python

### ISSUE THREAD

**Issue by ColinKennedy** [Wansmer/treesj#109]
Given a Python file such as

```python
bar(zzzz, {"thing": "blah"})
```

Call `:TSJToggle` twice and it becomes

```python
bar(
    zzzz,
    { "thing": "blash"},
)
```

and then

```python
bar(zzzz, { "thing": "blash", },)
```

Note the extra ` ` around `{ ` and ` }` which weren't there before, plus the extra two `,`s within `, },)`

**Comment by Wansmer** [comment]
Check your preset for Python and update ts-parsers.
I checked the given example with the default preset and it works correct.

https://github.com/Wansmer/treesj/assets/46977173/8c992912-8715-4c10-96f9-7a914beaf3c8

**Comment by ColinKennedy** [comment]
You're right, it was the preset. I misused `last_separator = true` by assigning it to `both`, instead of just `split` like I'd intended.

The new configuration

```lua
-- Set up the treesitter nodes for the Python language.
local lang_utils = require("treesj.langs.utils")
local options = {
    join = { space_in_brackets = false },
    split = { last_separator = true },
}

require("treesj").setup(
    {
        use_default_keymaps = false,
        langs = {
            python = {
                argument_list = lang_utils.set_preset_for_args(options),
                assignment = { target_nodes = { "list", "set", "tuple", "dictionary" } },
                call = { target_nodes = { "argument_list" } },
                dictionary = lang_utils.set_preset_for_dict(options),
                list = lang_utils.set_preset_for_list(options),
                parameters = lang_utils.set_preset_for_args(options),
                set = lang_utils.set_preset_for_list(options),
                tuple = lang_utils.set_preset_for_list(options),
            }
        }
    }
)
```

Now gives the results I want (trailing separator + no excess spaces)

https://github.com/Wansmer/treesj/assets/10103049/8a000af4-fb74-4159-934a-cbdfa9f71f35

Thanks for the plug-in btw. It's been super helpful
