### ISSUE TITLE
[Feature Request]: Toggle between <a></a> and <a /> (if tag is empty) in HTML/JSX etc.

### ISSUE THREAD

**Issue by phelipetls** [Wansmer/treesj#110]
Does it make sense to have this feature? Emmet has it, it's called https://docs.emmet.io/actions/split-join-tag/

**Comment by Wansmer** [comment]
It's already possible to tune with `format_tree` [option](https://github.com/Wansmer/treesj#option-format_tree), but I'm not sure if that should be in default html's preset. Because it is not a split/join, but formatting or replacing nodes.
