### ISSUE TITLE
FR: when on comment, just run `gqq`

### ISSUE THREAD

**Issue by chrisgrieser** [Wansmer/treesj#116]
Minor idea:

Right now, just gives out a warning and does nothing when on a comment. How about having treesj simply split the comment by `textwidth` instead? Essentially use `gqq` as behavior when trying to splitjoin a comment, since it's a straightforward and common split-join operation one does on comments.

Could add this feature as opt-in, since not everyone would like it, I guess

**Comment by Wansmer** [comment]
Thanks for the idea.

In the future, I plan to add a fallback option for nodes that can't be split/join using `treesj`. Then it will be possible to customize the execution of third-party scripts for each node, including `gqq`.

**Comment by Wansmer** [comment]
Done in #125:
E.g.:
```lua
lua = {
  comment = {
    both = {
      fallback = function(tsn)
        vim.cmd('normal! gww')
      end,
    },
  },
}
```

**Comment by chrisgrieser** [comment]
thank you! how would I add that to the `setup` call? (The docs are not totally apparent to me on this regard)

Also, am I correct that this means the comment fallback has to be added once for every single language I use?

**Comment by Wansmer** [comment]
Example for `lua`:

```lua
return {
  'Wansmer/treesj',
  config = function()
    require('treesj').setup({
      langs = {
        lua = {
          comment = {
            both = {
              fallback = function(tsn)
                vim.cmd('normal! gww')
              end,
            },
          },
        },
      },
    })
  end,
}
```

Yes, customize via `fallback` for each language for the `comment` node. You can loop through `require('treesj.langs').presets` and add for each language.
```lua
config = function()
  local langs = require('treesj.langs').presets
  for _, nodes in pairs(langs) do
    nodes.comment = {
      both = {
        fallback = function(tsn)
          vim.cmd('normal! gww')
        end,
      },
    }
  end

  require('treesj').setup({
    max_join_length = 1000,
  })
end,
```

**Comment by chrisgrieser** [comment]
thanks for the response!

So I tried both of your suggestions, and it does not work for me, giving me the warning: `Language "comment" is not configured`. My assumption would be that this is because of the [treesitter-parser for comments](https://github.com/stsewd/tree-sitter-comment).

Running `:Inspect` on a comment in lua gives me this output:
```
Treesitter
  - @comment.lua links to Comment lua
  - @spell.lua links to @spell lua
  - @spell.comment links to @spell comment

Semantic Tokens
  - @lsp.type.comment.lua links to @lsp.type.comment priority: 125
```

**Comment by Wansmer** [comment]
I don't use the parser for `comment`. Try to use this code, this one worked (tried it in two different languages).

```lua
      langs = {
        comment = {
          source = {
            both = {
              fallback = function(tsn)
                vim.cmd('normal! gww')
              end,
            },
          },
        },
      },
```
However, I'm not sure if `source` is the only node in `comment`, the tree is not detailed by `playground`.

**Comment by chrisgrieser** [comment]
hmm, this does not seem to work for me. 🤔 

before:
<img width="1542" alt="Pasted image 2023-08-06 at 20 09 56@2x" src="https://github.com/Wansmer/treesj/assets/73286100/61a8b2bc-fba2-4b9e-ab31-37658e4286f8">
after:
<img width="704" alt="Pasted image 2023-08-06 at 20 10 31@2x" src="https://github.com/Wansmer/treesj/assets/73286100/1aa379c1-45a0-44e4-83c8-63b84a02c5e4">

**Comment by Wansmer** [comment]
@chrisgrieser I'm sorry, but I don't know why it's not working for you. Are you sure you have updated `treesj`?
Here is an example of how it works for me with the settings I gave above:

https://github.com/Wansmer/treesj/assets/46977173/a94f87df-e52d-4875-a42b-80983c0b0e0b

**Comment by chrisgrieser** [comment]
ugh, sorry, it wasn't working because I forgot to update the plugin 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 

That was really dumb of me. Sorry for wasting your time! After updating everything works perfectly.
