### ISSUE TITLE
Can only split/join/toggle once

### ISSUE THREAD

**Issue by kevintraver** [Wansmer/treesj#118]
Can only split/join/toggle once.

The split/join/toggle actions works fine the first time, but when trying to do a split/join/toggle again then nothing happens.

Im on NVIM v0.9.1

Ive tested with a clean config and only *_treesj_* and *_treesitter_*.

![screenshot](https://github.com/Wansmer/treesj/assets/196406/e3853d24-d291-4697-9572-852d16361b31)

**Comment by Wansmer** [comment]
I can't reproduce this bug. Does it still reproduce for you? If so, please share the minimum configuration that reproduces the bug.

**Comment by alextricity25** [comment]
I'm getting the same thing. Here is my config:
```
require('treesj').setup({
    -- Use default keymaps
    -- (<space>m - toggle, <space>j - join, <space>s - split)
    use_default_keymaps = false,

    -- Node with syntax error will not be formatted
    check_syntax_error = false,

    -- If line after join will be longer than max value,
    -- node will not be formatted
    max_join_length = 120,

    -- hold|start|end:
    -- hold - cursor follows the node/place on which it was called
    -- start - cursor jumps to the first symbol of the node being formatted
    -- end - cursor jumps to the last symbol of the node being formatted
    cursor_behavior = 'hold',

    -- Notify about possible problems or not
    notify = true,
    langs = { lua = require( 'treesj.langs.lua' ), },

    -- Use `dot` for repeat action
    dot_repeat = true,
})
```
![2023-08-04_20-43-11 (1)](https://github.com/Wansmer/treesj/assets/4964964/c5285e7d-3744-40f3-9ac1-745997ce5a1a)

**Comment by Wansmer** [comment]
I found what the problem was: it required tree reparsing after changing the buffer text.

**Comment by alextricity25** [comment]
Can confirm it's fixed and working as expected now. Thanks @Wansmer!

**Comment by alextricity25** [comment]
@Wansmer Actually, I may have spoken too soon. It looks like there is a problem with the way treesj reads the current buffer. 
When I add new code to a block, then run `TSJToggle`, the new code disappears 😢 
![2023-08-05_11-53-25 (3)](https://github.com/Wansmer/treesj/assets/4964964/578a74f2-7570-46f6-b307-40dfdfc54545)

**Comment by Wansmer** [comment]
> @Wansmer Actually, I may have spoken too soon. It looks like there is a problem with the way treesj reads the current buffer.
> When I add new code to a block, then run `TSJToggle`, the new code disappears 😢

Really unexpected... I will fix it.

**Comment by Wansmer** [comment]
@alextricity25 It should be working now. (#121)

**Comment by alextricity25** [comment]
@Wansmer It works! Just tried it with typescript too and it works like a charm. Thank you!

**Comment by kevintraver** [comment]
One other potential issue, but it might be more of an issue with your other plugin [sibling-swap.nvim](https://github.com/Wansmer/sibling-swap.nvim):

After using _toggle_, I am then unable to swap arguments using _sibling-swap_.

Was just thinking this might be a buffer related issue.

**Comment by Wansmer** [comment]
> Was just thinking this might also be a similar buffer related issue.

Yes, it looks like something has changed in the way the treesitter works.

**Comment by kevintraver** [comment]
Both plugins are working now!! Thank you!
