### ISSUE TITLE
[bug] empty function calls get split as well

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [Wansmer/treesj#12]
```lua
local function test()
    print('hello')
end

test()
    ^^ call TSJSplit with cursor on/within parens

--- becomes

test(
)
```

Using default config, in Lua file.
can a check be added so that splits dont happen when no elements are present?

**Comment by Wansmer** [comment]
I am not sure if that is the bug. I am purposefully no handle empty brackets. Maybe it wrong. 
Which result should be by your opinion?

**Comment by ViRu-ThE-ViRuS** [comment]
I can't really think of a situation where one would use the code format:
``` c++
test(
)
```
most auto formatters will reverse this change anyways (AFAIK).
If it is useful, then maybe a toggle / option in the config would fit nicely for "empty" blocks.

**Comment by Wansmer** [comment]
I'll add in the future an option for setting this case.
