### ISSUE TITLE
Cant disable the preset keybindings.

### ISSUE THREAD

**Issue by GaurAfro** [Wansmer/treesj#127]
# I am new to reporting an issue, so please excuse me if I don't do it right.

### Here is how I am trying to modify them:
---
## From my (lazy) ~/.config/nvim/lua/pluginslist.lua
``` lua
    {
        'Wansmer/treesj',
        -- keys = { '<space>m', '<space>j', '<space>s' },
        dependencies = { 'nvim-treesitter/nvim-treesitter' },
        config = function()
            require('treesj').setup({--[[ your config ]]})
        end,
    },
```
---
## From my ~/.config/nvim/after/plugin/treesj.lua
``` lua
-- Load TreesJ modules
local tsj = require('treesj')

-- local langs = {--[[ configuration for languages ]]}

tsj.setup({
  ---@type boolean Use default keymaps (<space>m - toggle, <space>j - join, <space>s - split)
  use_default_keymaps = false,
  ---@type boolean Node with syntax error will not be formatted
  check_syntax_error = true,
  ---If line after join will be longer than max value,
  ---@type number If line after join will be longer than max value, node will not be formatted
  max_join_length = 120,
  ---Cursor behavior:
  ---hold - cursor follows the node/place on which it was called
  ---start - cursor jumps to the first symbol of the node being formatted
  ---end - cursor jumps to the last symbol of the node being formatted
  ---@type 'hold'|'start'|'end'
  cursor_behavior = 'hold',
  ---@type boolean Notify about possible problems or not
  notify = true,
  ---@type table Presets for languages
  -- langs = lu._prepare_presets(langs.presets),
  ---@type boolean Use `dot` for repeat action
  dot_repeat = true,
  ---@type nil|function Callback for treesj error handler. func (err_text, level, ...other_text)
  on_error = nil,
})

-- Load which-key for keybinding docs
local wk = require("which-key")

-- Register TreesJ keybindings
wk.register({
    ["<leader>tst"] = { function() require('treesj').toggle() end, "Toggle node under cursor" },
    ["<leader>tss"] = { function() require('treesj').split() end, "Split node under cursor" },
    ["<leader>tsj"] = { function() require('treesj').join() end, "Join node under cursor" },
})
```

**Comment by Wansmer** [comment]
You only need to call `require('treesj').setup()` once. In the examples you have shown, there are two calls - one with default settings and one with changes. You need to remove the first call from the `config` function.

**Comment by GaurAfro** [comment]
Thanks that fixed it

**Comment by unphased** [comment]
I did not know you can assign bindings via which-key directly as a rather readable way to ensure a description is registered for a bind. nice. 

The reason I'm here is because i tried for a while to modify the `keys = { '<space>m', '<space>j', '<space>s' },` field in the plugin definition for Lazy, but now I realize maybe this is here misleadingly as a comment and not actually something being referenced...

**Comment by catdadcode** [comment]
> I did not know you can assign bindings via which-key directly as a rather readable way to ensure a description is registered for a bind. nice.
> 
> The reason I'm here is because i tried for a while to modify the `keys = { '<space>m', '<space>j', '<space>s' },` field in the plugin definition for Lazy, but now I realize maybe this is here misleadingly as a comment and not actually something being referenced...

Exact same reason I'm here too lol. Came to see if anyone was asking about the default Lazy.nvim keybindings not working.

It works for me if I do a proper [LazyKeySpec](https://github.com/folke/lazy.nvim?tab=readme-ov-file#%EF%B8%8F-lazy-key-mappings) and set `use_default_keymaps = false` like this:

```lua
return {
	"Wansmer/treesj",
	lazy = false,
	keys = {
		{ "gj", "<CMD>TSJToggle<CR>", desc = "Toggle Inline/Block" },
	},
	dependencies = { "nvim-treesitter/nvim-treesitter" },
	config = function()
		require("treesj").setup({
			use_default_keymaps = false,
		})
	end,
}
```
