### ISSUE TITLE
Typescript: Split/Join some arrow functions results in invalid code

### ISSUE THREAD

**Issue by afgomez** [Wansmer/treesj#132]
:wave:, thanks for building this plugin!

I found an issue when splitting or joining arrow functions in Typescript. The plugin seems to have trouble handing blocks without a `return` statement in the function body.

I have the following function

```ts
export async function pretendDelay() {
  const delay = Math.floor(Math.random() * 1000); // Between 0 and 1 seconds
  return new Promise((resolve) => {
    setTimeout(resolve, delay);
  });
}
```

Note that the `setTimeout` doesn't have a `return`.

- When I try to join the arrow function inside the `Promise`, the plugin tries to return the value of the block (changing the semantics), and places an extra semicolon in the end (adding a syntax error).
- If I try to revert back splitting the function, it now adds a `return` statement, and keeps the invalid semicolon.

https://github.com/Wansmer/treesj/assets/57448/7a916db5-3377-4585-be74-79b5cf474616

**Comment by Wansmer** [comment]
Done #133
