### ISSUE TITLE
[TreeSJ]: Cannot join "table_constructor" containing node from one of this: { "commend" }

### ISSUE THREAD

**Issue by sumanth-lingappa** [Wansmer/treesj#138]
Please help. I am not sure what is wrong in my configuration.

My config is
```lua
require("lazy").setup({
{
    'Wansmer/treesj',
    keys = { '<space>m', '<space>j', '<space>s' },
    dependencies = { 'nvim-treesitter/nvim-treesitter' },
    config = function()
      require('treesj').setup({ --[[ your config ]] })
    end,
  },
})
```

The above gets lazy loaded till I press one of `<space>m', '<space>j' or '<space>s'.

After that when I press `:TSJToggle`, it is giving me the below error

```
[TreeSJ]: Cannot join "table_constructor" containing node from one of this: { "commend" }
```

**Comment by Wansmer** [comment]
By default, `treesj` does not format nodes if they contain a comment, as this will cause the resulting code to become non-valid. 

If you remove a comment from a node you want to split or join, the error will go away.

**Comment by sumanth-lingappa** [comment]
Got it. 

Is it possible to document it somewhere?

**Comment by Wansmer** [comment]
> Is it possible to document it somewhere?

This is already documented here: https://github.com/Wansmer/treesj#basic-node
