### ISSUE TITLE
[golang] "The current node is already splitted" when attempting to split a multiline statement

### ISSUE THREAD

**Issue by protiumx** [Wansmer/treesj#149]
Split stopped working for multiline statements. e.g.
```go
func New(param1 string, param2 int,
param3 bool) { ... }

var t := Some{ fieldA: "",
fieldB: 0}
```
This was working before https://github.com/Wansmer/treesj/commit/ecc658432129a23abb5b58e6f59b8bcfb9a961a4
Would it be possible to restore it?

This functionality is extremely helpful when dealing with bad formatted code (multiline).

**Comment by Wansmer** [comment]
> This functionality is extremely helpful when dealing with bad formatted code (multiline).

`treesj` is not a formatter, maybe better to use built-in lsp formatter to format code? :-)

> Would it be possible to restore it?

I don't want to restore it, but maybe later I will add an option to manage this behavior.
