### ISSUE TITLE
JS/TS: split-join should support curly-less if statements

### ISSUE THREAD

**Issue by chrisgrieser** [Wansmer/treesj#150]
With if-statements, treesj can toggle between these:
```js
if (foobar) {
	console.log("foobar");
}

if (foobar) { console.log("foobar"); }
```

But more desirable would be this:

```js
// A
if (foobar) {
	console.log("foobar");
}

// B
if (foobar) console.log("foobar");
```

from A to B, I can get by adding my own config:

```lua
javascript = {
	statement_block = {
		join = {
			format_resulted_lines = function(lines)
				if #lines ~= 3 or lines[1] ~= "{" then return lines end
				local curlyBracketsRemoved = vim.trim(lines[2])
				return { curlyBracketsRemoved }
			end,
		},
	},
},
```

However, I don't really know how to get from B to A. In any case, I think curly-less if-statements should probably be the default for js/ts?

**Comment by Wansmer** [comment]
> I think curly-less if-statements should probably be the default for js/ts?

I don't think so, because it's a matter of style, and every developer has his own opinion about style.
You can add something like this in your config for the `if_statement` handle:

```lua
javascript = {
  statement_block = {
    join = {
      format_tree = function(tsj)
        if tsj:tsnode():parent():type() == "if_statement" then
          tsj:remove_child({ left = "{", right = "}" })
        else
          local stmt_join_fb = require("treesj.langs.javascript").statement_block.join.fallback
          stmt_join_fb(tsj)
        end
      end,
    },
  },
  expression_statement = {
    join = {
      enable = false,
    },
    split = {
      enable = function(tsn)
        return tsn:parent():type() == "if_statement"
      end,
      format_tree = function(tsj)
        tsj:wrap({ left = "{", right = "}" })
      end,
    },
  },
}
```

**Comment by chrisgrieser** [comment]
> I don't think so, because it's a matter of style, and every developer has his own opinion about style.

I didn't express myself clearly, sorry.  What I meant was that you are trying to split `if (foobar) console.log("foobar");`, it does not work. When the user tries to do a split-command on a single-line-if-statement-without-braces, it is I think unambiguous that the intention is to create a multi-line-if-statement. For *this* case, it might make sense to add the `expression_statement` from above to the defaults.

---

> You can add something like this in your config for the if_statement handle:

Thank you, that works wonderfully! 🥳  (just need to use `tsj:remove_child { "{", "}" }` though)

Love the customizability of the plugin, which is probably only limited by needing to learn all the treesitter stuff.

**Comment by mmanning2-chwy** [comment]
Having some troubles with an edge case using the config example above...

When you have the following:

```ts
if (foo == 'bar') return console.log('bar')
```

You cannot split, but joining works as expected.
Adding the following:
```lua
return_statement = {
  split = {
    enable = function(tsn)
      return tsn:parent():type() == "if_statement"
    end,
    format_tree = function(tsj)
      tsj:wrap({ left = "{", right = "}" })
    end,
  },
},
```
Will allow you to split. However now when you join you now get:
```ts
if (foo == 'bar') returnconsole.log('bar')
```
I know the modified `statement_block` with the `if_statement` parent is doing the wrap, not sure why it's stripping the space.

Been tinkering and can't seem to get it to work.

**Comment by Wansmer** [comment]
> I know the modified `statement_block` with the `if_statement` parent is doing the wrap, not sure why it's stripping the space.

Try with this:
```lua
          statement_block = {
            join = {
              format_tree = function(tsj)
                if tsj:tsnode():parent():type() == "if_statement" then
                  tsj:remove_child({ "{", "}" })
                  tsj:update_preset({ recursive = false }, "join") -- <- New line
                else
                  local stmt_join_fb = require("treesj.langs.javascript").statement_block.join.fallback
                  stmt_join_fb(tsj)
                end
              end,
            },
          },
```

**Comment by mmanning2-chwy** [comment]
That works thank you! Love the plugin.
