### ISSUE TITLE
Is `nvim-treesitter` still a dependency?

### ISSUE THREAD

**Issue by boltlessengineer** [Wansmer/treesj#153]
I see [this commit](https://github.com/Wansmer/treesj/commit/bdf9276c5d84ab19cc3091b34c22a9d8f8447eca) removing the `nvim-treesitter` from dependency, and I can’t find treesj using it from codebase.
But README is still pointing that it’s needed as dependency.

**Comment by Wansmer** [comment]
The `nvim-treesitter` plugin is not needed as a dependency, but parsers are still needed. Usually parsers are installed via `nvim-treesitter`.

But you are right, I should clarify this point in the README.

**Comment by Wansmer** [comment]
The README updated (dd46d5340e41f925d5acb5f65f5524e0999c35da)
