### ISSUE TITLE
Please help to configure Pug

### ISSUE THREAD

**Issue by Artem-Schander** [Wansmer/treesj#16]
Hi, thank you for this awesome tool.
I'm struggling to configure it for [pug](https://pugjs.org/api/getting-started.html).
I've looked into the `html` implementation but did not find anything useful. I always get the message:
```
Cannot "join" node longer than 120 symbols. Check your settings to change it.
```

Here is my current pug config:
```lua
local langs = require('treesj.langs')
local u = require('treesj.langs.utils')
langs["pug"] = {
    attributes = u.set_default_preset({
        both = {
            space_separator = 1,
            separator = ' '
        },
    }),
}
```

**Comment by Wansmer** [comment]
Hi, you just need to change 'max_join_length' to bigger than 120: https://github.com/Wansmer/treesj#plugin-configuration

**Comment by Artem-Schander** [comment]
🤦 thanks
