### ISSUE TITLE
Add if, unless and conditional for Perl

### ISSUE THREAD

**Issue by pjcj** [Wansmer/treesj#160]
Perl has `if`, `unless` and `conditional` in pretty much the exact way that Ruby does (or the other way around really).  Is there any chance of getting those added?

My apologies for making this a request - I'm not in a position to put together a PR at the moment but I wanted to create a ticket at least.

**Comment by Wansmer** [comment]
I can add new nodes for Perl, but I need code examples since I don't write in Perl. Please send me examples for `if`, `unless` and `conditional` nodes in `split` and `join` states ([an example of how it should look like](https://github.com/Wansmer/treesj/blob/main/tests/sample/index.pl)).

**Comment by Wansmer** [comment]
Since no sample code is provided, I close the issue
