### ISSUE TITLE
Split HTML delete PHP content

### ISSUE THREAD

**Issue by jsongerber** [Wansmer/treesj#162]
Hi,
I'm enjoying your plugin for a certain time and it works really well.

I noticed a bug, I'm not sure if it's due to my config or not, but when I'm splitting an HTML tag that contain PHP code, the PHP  part gets deleted, it happens in HTML tag content and attribute, here's a video demonstrating:

https://github.com/user-attachments/assets/93a822ad-6e2c-4644-9dfa-af01cd345f42

I'm only using the :TSJSplit command in the demo.
I tried to fix but tree-sitter code/queries are really out of my understanding.

Here's my config:
```
return {
  'Wansmer/treesj',
  keys = {
    {
      'gs',
      '<cmd>:TSJSplit<CR>',
      'n',
      desc = '[S]plit',
    },
    {
      'gS',
      '<cmd>:TSJJoin<CR>',
      'n',
      desc = '[J]oin',
    },
  },
  config = function()
    require('treesj').setup {
      use_default_keymaps = false,
    }
  end,
}
```

And here's a minimal snippet where the bug happens, you need to `set ft=php`:
```
<div <?php echo $test ?>><?php echo $description; ?></div>
```

I'm on MacOS and
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1725453128

**Comment by Wansmer** [comment]
Hi. This looks like a special kind of `php` parsing feature. Try executing `:InspectTree<Cr>` and you will see something like this:

```scheme
(program ; [0, 0] - [1, 0]
  (document ; [0, 0] - [1, 0]
    (element ; [0, 0] - [0, 58]
      (start_tag ; [0, 0] - [0, 25]
        (tag_name)) ; [0, 1] - [0, 4]
      (end_tag ; [0, 52] - [0, 58]
        (tag_name)))) ; [0, 54] - [0, 57]
  (text) ; [0, 0] - [0, 5]
  (php_tag) ; [0, 5] - [0, 10]
  (echo_statement ; [0, 11] - [0, 21]
    (variable_name ; [0, 16] - [0, 21]
      (name))) ; [0, 17] - [0, 21]
  (text_interpolation ; [0, 22] - [0, 30]
    (text) ; [0, 24] - [0, 25]
    (php_tag)) ; [0, 25] - [0, 30]
  (echo_statement ; [0, 31] - [0, 49]
    (variable_name ; [0, 36] - [0, 48]
      (name))) ; [0, 37] - [0, 48]
  (text_interpolation ; [0, 50] - [1, 0]
    (text))) ; [0, 52] - [1, 0]
```

Here you can see that the nodes `element`(in `document`) and `phptag` are on the same level, although `phptag` is expected to be inside `element`. So when `treesj` receives the node text from the tree-sitter api, there is no `phptag` text there, so it cannot be added to the final result since it was not received.

So this is not a bug of `treesj`.

**Comment by jsongerber** [comment]
I understand, thank you for your quick response, I'll close this issue.
