### ISSUE TITLE
Bug: Joining string arguments in python deletes string content

### ISSUE THREAD

**Issue by chrisgrieser** [Wansmer/treesj#164]
Given this python code:

```py
print(
    "one",
    "two",
)
```

When using `TSJoin`, results in:
```py
print("", "")
```

**Comment by Wansmer** [comment]
I can't reproduce it:

https://github.com/user-attachments/assets/34dbbddc-c984-43c9-ac79-453fcf7f7164

Please give the minimum configuration and sequence of actions needed to reproduce the problem. Make sure you have the latest Python parser.
