### ISSUE TITLE
FR: Support for functions and if-statements

### ISSUE THREAD

**Issue by chrisgrieser** [Wansmer/treesj#22]
Thanks for this plugin, I really like the idea of auto-detection :)

My feature suggestions would be to extend the plugin functionality to also work for functions and if-statements, as I often find myself splitting/joining them in these situations.

 Below are two examples in lua.

```lua
function foo () return "bar" end

function foo ()
  return "bar"
end
```

```lua
if foo then return end

if foo then
  return
end
```

**Comment by Wansmer** [comment]
Hi! Thanks for suggestion, this task already placed in my todo-list. In the future, it will be implemented.

**Comment by chrisgrieser** [comment]
thank you so much, it works like a charm and it makes refactoring *so* much more pleasant.
