### ISSUE TITLE
`noexpandtab` is not respected when splitting

### ISSUE THREAD

**Issue by chrisgrieser** [Wansmer/treesj#25]
to reproduce

```lua
-- before
if 1 == 1 then print("beep") end
```

run this three commands (listchars only changed for visibiliy)
```viml
:set noexpandtab
:lua vim.opt.listchars = "tab:> ,space:."
:TSJSplit
```

```lua
-- after
if 1 == 1 then
    print("beep") -- has four spaces, not a tab character
end
```

**Comment by Wansmer** [comment]
At the moment, TreeSJ work only with spaces, no with tab character. I'll think about to add a functionality to detect of type of tabulation. Good remark.

**Comment by chrisgrieser** [comment]
thank you :)
