### ISSUE TITLE
repeat last action using `.` support

### ISSUE THREAD

**Issue by lalitmee** [Wansmer/treesj#27]
Thanks for this awesome plugin. 

I think it would be great if the repeat last action using **dot**(`.`) can be implemented.

**Comment by jpoppe** [comment]
Nice refererence which could maybe help with implementation 😇: https://www.vikasraj.dev/blog/vim-dot-repeat

**Comment by Wansmer** [comment]
Implemented with #61 

Thanks @jpoppe for link to article!
