### ISSUE TITLE
[feat] Add Golang support

### ISSUE THREAD

**Issue by alphatroya** [Wansmer/treesj#31]
I think the Go language can be a good candidate for adding to preset languages.

**Comment by Wansmer** [comment]
Yeah, I am planning to add Go, but I have a problem with code examples for doing preset. You can help me and send examples of code which can be split/join.
E.g.
```javascript
// RESULT OF JOIN (node "object", preset default)
const obj = { one: 'one', two: [ 1, 2 ], three: { one: 'one', two: [ 1, 2 ] } };

// RESULT OF SPLIT (node "object", preset default)
const obj = {
  one: 'one',
  two: [ 1, 2 ],
  three: { one: 'one', two: [ 1, 2 ] },
};
```
but with Go.
