### ISSUE TITLE
No indent in LUA files

### ISSUE THREAD

**Issue by Tummetott** [Wansmer/treesj#45]
Hello, 

When splitting the following code

```lua
local dict = { 'a', 'b', 'c' }
```

the result is:

```lua
local dict = {
'a',
'b',
'c',
}
```

My question: Why are the dict elements not properly indented like it's done in e.g. `.js` documents? Is this intended behaviour? How can I change this behaviour? I would expect the code to be like:

```lua
local dict = {
    'a',
    'b',
    'c',
}
```

**Comment by Wansmer** [comment]
Hello, I think, you have 'shiftwidth' equals 0 for filetype 'lua'.
Indent calculating on value of 'shiftwidth'.
Try `:lua =vim.bo.shiftwidth`. If it will be '0', set option `shiftwitdh` bigger than 0 in your init.lua.

**Comment by Tummetott** [comment]
Thank you for the quick response.
Yes it's true i have `shiftwith = 0` because when zero, it defaults to `tabstop`. And I have `tabstop = 4`. 
Interestingly, when inside e.g.`.js` or `.py` files, the indent works properly with `shiftwith = 0`. Is this intended, that `.lua` files are treated differently?

Setting shiftwith to 4 would solve my problem, however I like having `shiftwith` bound to my `tabstop`. If it's not too complicated, I'd love to see a fix but otherwise i'll just change my shiftwith value.

Great plugin by the way ❤️

**Comment by Wansmer** [comment]
Thanks for feedback.
I not sure what it needs to be fixed, because `shiftwidth` is a default for builtin neovim indent engine.

Try set `expandtab` to false – it will save tabs instead of spaces and you can use `shiftwidth`.

> Is this intended, that .lua files are treated differently?

I think, it sets by neovim's directly. Neovim have builtin preset for different filetypes.

**Comment by Tummetott** [comment]
Yes it's true, `shiftwith` is a default. However you can not take that value literally.

Output from `:help shiftwith`:
> Number of spaces to use for each step of (auto)indent.  
> Used for 'cindent', >>, <<, etc. When zero the 'ts' value will be used.

That means, whenever `shiftwidth` is set to zero, the true value of shiftwidth is the value of `tabstop`. The zero just denotes, that tabstop and shiftwith are bound together.

You're using the shiftwidth literally in two palces:
https://github.com/Wansmer/treesj/blob/023db2f52607d89cb800e4eeed83377ae6f5fb78/lua/treesj/utils.lua#L368
https://github.com/Wansmer/treesj/blob/10aed3c6a799d483e5eec247e71e84b49864426b/lua/treesj/treesj/init.lua#L72

An additional check like the following would solve the issue:
```lua
if shiftwidth == 0 then
    shiftwidth = vim.api.nvim_buf_get_option(0, 'tabstop') 
end
```

I'd do a PR, but i don't understand the logic of your plugin. Do when do you use the `calc_indent()` and when the `build_tree()` function? Do you need to change it in both places? I guess you have a better understanding of that.

**Comment by Tummetott** [comment]
> I think, it sets by neovim's directly. Neovim have builtin preset for different filetypes.

You're right with that. The global value was overwritten by ftplugin. Thanks for the clarification

**Comment by Wansmer** [comment]
> That means, whenever `shiftwidth` is set to zero, the true value of shiftwidth is the value of `tabstop`. The zero just denotes, that tabstop and shiftwith are bound together.

I use `shiftwidth` in a logic way – because it about indentation. `tabstop` it only about width of tabulation.
I'll learn a little more about interconnections of `tabstop` and `shiftwidth`. At the moment, `sw` looks the best values for use.

**Comment by f1rstlady** [comment]
> An additional check like the following would solve the issue:
> 
> ```lua
> if shiftwidth == 0 then
>     shiftwidth = vim.api.nvim_buf_get_option(0, 'tabstop') 
> end
> ```
The `shiftwidth()` function returns the effective value of `'shiftwidth'; see `:h shiftwidth()`.
