### ISSUE TITLE
Rust: split match arms into blocks

### ISSUE THREAD

**Issue by Rodrigodd** [Wansmer/treesj#48]
I have migrated from [splitjoin.vim] to this plugin. This plugin works great, but my favorite feature of splitjoin.vim was how it could split expression in match arms into a block. This feature is a little broken in splitjoin.vim, and I always planned to remake it using tree sitter before I encounter this plugin.

[splitjoin.vim]: https://github.com/AndrewRadev/splitjoin.vim

I was planning to implement this myself and submit a PR, but from what I looked, this plugin only has support for splitting nodes with clear delimiters. So I became unsure to how to implement it.

```rust
// It would allow spliting a "match_arm.value"
match x {
    _ => 12
}
// Into this
match x {
    _ => {
        12
    }
}
```

This could also be extended to apply to Rust closures (`|| 1` into `|| { 1 }`) and JavaScript arrow function (`() => 1` into `() => { return 1; }`), for example.

If you could provide any directions, I can try implementing it.

**Comment by Wansmer** [comment]
I am planning to implement this feature in the future. (It looks simple, but require some structural changes to finding nodes to split/join).

If you have another examples for this case in another languages – please send – it will help.

> I was planning to implement this myself and submit a PR, but from what I looked, this plugin only has support for splitting nodes with clear delimiters. So I became unsure to how to implement it.

This plugin build yet one tree around treesitter tree. It means, that you can add new nodes with any content in any tree branch. In case `x => { x; }` to `x => x;`, first need to implement finding node by `tsnode:field()`. At the moment, finding only by `tsnode:type()`.

**Comment by Wansmer** [comment]
Done at #77
