### ISSUE TITLE
[feat] add C/C++ support

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [Wansmer/treesj#5]
hey! amazing work on this plugin, works very well for me in some of the languages I have tested it on!

I wanted to request support for C/C++ as well, as it would be very useful and the fact that there are very few options (if any) for these languages for this level of functionality. I am aware that it might be a complicated endeavor (as suggested by discussions in `splitjoin.vim` plugin), but its good to start a new discussion. 

I think it would be a great addition to this plugin, and will attract many more devs and appreciation!

**Comment by Wansmer** [comment]
Hi! Thanks for feedback. Can you send few examples of c++: 'result of SPLIT'/'result of JOIN' (like in [tests](https://github.com/Wansmer/treesj/blob/main/tests/sample/index.js))?
I didn't use c++ in my work and no know its syntax. I think, if c++ have similar structure, `TreeSJ` will handle it.

Or you can try configured c++ according [README.md](https://github.com/Wansmer/treesj#nodes-configuration) and open a PR.

**Comment by ViRu-ThE-ViRuS** [comment]
sure! I can see what I can get this working with, just starting to get familiar with Treesitter.
but for a reference, checkout this issue on `splitjoin.nvim`

https://github.com/AndrewRadev/splitjoin.vim/issues/33#issuecomment-44127589

**Comment by ViRu-ThE-ViRuS** [comment]
just from a quick view, progress would require support for multiple `separators` configurable via a list like `no_format_with` is.  eg: this would enable `and`, `or`, `&&`, `||`, and so on to be used together in as one `separator` type.

**Comment by Wansmer** [comment]
Later, I'll look at the tree structure that the treesitter gives. I think that there should be no problems for c/c++ support.

**Comment by Wansmer** [comment]
> just from a quick view, progress would require support for multiple `separators` configurable via a list like `no_format_with` is. eg: this would enable `and`, `or`, `&&`, `||`, and so on to be used together in as one `separator` type.
> 
> also, there is a crash, its hard to explain how to reproduce, but it might be a missing bounds check which can just be patched:
> 
> ```
> || Error executing Lua callback: ...e/nvim/site/pack/packer/opt/treesj/lua/treesj/format.lua:67: Cursor position outside buffer
> || stack traceback:
> || 	[C]: in function 'nvim_win_set_cursor'
> || 	...e/nvim/site/pack/packer/opt/treesj/lua/treesj/format.lua:67: in function '_format'
> || 	...are/nvim/site/pack/packer/opt/treesj/lua/treesj/init.lua:20: in function <...are/nvim/site/pack/packer/opt/treesj/lua/treesj/init.lua:19>
> ```

Can you open a separate issue and send a code, preset and cursor position where you call a plugin?

**Comment by ViRu-ThE-ViRuS** [comment]
> Later, I'll look at the tree structure that the treesitter gives. I think that there should be no problems for c/c++ support.

I agree, some of the use cases are very easily implemented:

``` lua
        cpp = {
            parameter_list = treesj_utils.set_preset_for_args(),
            argument_list = treesj_utils.set_preset_for_args(),
            initializer_list = treesj_utils.set_preset_for_list(),
            compound_statement = treesj_utils.set_preset_for_list({
                both = {
                    separator = ';',
                    last_separator = true,
                    no_format_with = {}
                }
            })
        },

```

ill keep looking at this, adding more cases as I find time and use.

**Comment by Wansmer** [comment]
@ViRu-ThE-ViRuS, send a code (block where you call plugin) too, please

**Comment by Wansmer** [comment]
> [AndrewRadev/splitjoin.vim#33 (comment)](https://github.com/AndrewRadev/splitjoin.vim/issues/33#issuecomment-44127589)

In the first fragment, it is a binary expression. I don't think what is the best way to format it with treesitter (because it is binary inside binary). But I also think, how implement this, but not in TreeSJ.
The second fragment you already configured in your preset. Or implied need similar formatting, when first argument stay on first line?

> [AndrewRadev/splitjoin.vim#33 (comment)](https://github.com/AndrewRadev/splitjoin.vim/issues/33#issuecomment-44130021)

About this, not sure. In my todos I have task to adapt TreeSJ for split/join blocks without brackets, but here separator stay before named nodes. I'll keep that scenario in mind for future development.

**Comment by ViRu-ThE-ViRuS** [comment]
> > [AndrewRadev/splitjoin.vim#33 (comment)](https://github.com/AndrewRadev/splitjoin.vim/issues/33#issuecomment-44127589)
> 
> In the first fragment, it is a binary expression. I don't think what is the best way to format it with treesitter (because it is binary inside binary). But I also think, how implement this, but not in TreeSJ. The second fragment you already configured in your preset. Or implied need similar formatting, when first argument stay on first line?

For the first fragment, it would make sense if clauses within `( )` are on one line, and if no grouping via `( )` is given, then just split them all into new lines. EG:
``` c++
if (a && b || c) {}
---
if (
    a &&
    b || 
    c
) {}
```
**NOTE:** One would prefer to have the first clause on the first line, and the last clause inline with `) {}` but I think thats a nit pick and its okay to not handle this edge case. 
The main point is to split the conditions into readable lines, after which any auto formatter can take care of the first and last lines as per its configuration. 

```c++
if((a && b) || c) {}
---
if (
    (a && b) ||
     c
) {}
```
 
If these groupings can be handled correctly by TreeSJ, it would be an amazing addition. 
I totally understand if cases like this are beyond the scope of this plugin.

**Comment by Wansmer** [comment]
#58, #59
