### ISSUE TITLE
Python: don't drop trailing comma from single-element tuple on join

### ISSUE THREAD

**Issue by mikaraunio** [Wansmer/treesj#56]
By default, TreeSJ drops the trailing comma when joining tuples, so:
```
(
  1,
)
```
becomes `(1)` instead of `(1, )`. This is a problem in Python if the tuple has only a single member, as the two forms mean different things: a parenthesized number vs. a tuple.

This can be easy to miss if the join happens as part of a nested collapse. Would be great if TreeSJ could automatically preserve the comma in this particular case when dealing with Python.

**Comment by Wansmer** [comment]
It makes sense, thanks!

**Comment by mikaraunio** [comment]
Thanks for the quick fix. Tested and works perfectly here.

Would there be an easy way to preserve the comma *only* with single-element tuples? With more elements, the trailing comma is still syntactically correct, but some linters will complain.

If not, certainly better to always keep the comma than to drop it.

**Comment by Wansmer** [comment]
At the moment this is not possible, but I will think about how to implement it in the future
