### ISSUE TITLE
Error ：search first

### ISSUE THREAD

**Issue by dnxxymcj** [Wansmer/treesj#62]
Why does it search first, is there something wrong with my configuration?

        branch main
        commit 950d06e

```lua
   Error  20:41:07 msg_show.lua_error Error executing Lua callback: /Users/cj/.local/share/nvim/lazy/treesj/lua/treesj/init.lua:25: Vim:E486: Pattern not found: rstnersitnrsetnei
stack traceback:
	[C]: in function 'normal'
	/Users/cj/.local/share/nvim/lazy/treesj/lua/treesj/init.lua:25: in function 'set_opfunc_and_format'
	/Users/cj/.local/share/nvim/lazy/treesj/lua/treesj/init.lua:30: in function 'format'
	/Users/cj/.local/share/nvim/lazy/treesj/lua/treesj/init.lua:37: in function </Users/cj/.local/share/nvim/lazy/treesj/lua/treesj/init.lua:36>

```

https://user-images.githubusercontent.com/7660888/217818285-9474d6b7-dae7-4dd0-8b82-306ebbca3631.mov

**Comment by Wansmer** [comment]
I can't reproduce this error.
Is this happens when you type in cmd `:TSJToggle` too or only with keymap `J`?

**Comment by dnxxymcj** [comment]
> I can't reproduce this error. Is this happens when you type in cmd `:TSJToggle` too or only with keymap `J`?

yes,  I reverted to the default configuration and still have the errors.

```lua
{
  'Wansmer/treesj',
  requires = { 'nvim-treesitter' },
  config = function()
    require('treesj').setup({--[[ your config ]]})
  end,
}
```

**Comment by dnxxymcj** [comment]
i use colemak keyboard layout
i map l to n...
```lua
map("", "l", "n", { noremap = true, silent = true })
```
```lua 
vim.cmd.normal('g@l')
```
g@l ---> g@n

What should I do in this situation?

**Comment by dnxxymcj** [comment]
```lua
map({ "n", "v" }, "l", "n", { noremap = true, silent = true })
```
done!

thank you!

**Comment by Wansmer** [comment]
Thanks for explanation why this error happens.
I replaced `vim.cmd.normal` to `vim.api.nvim_feedkeys` in #63, and now it should work despite key remapping.
