### ISSUE TITLE
Ruby: split-join bracketed blocks into do-end blocks

### ISSUE THREAD

**Issue by cbochs** [Wansmer/treesj#66]
Ruby uses different delimiters depending on whether a [block](https://www.rubyguides.com/2016/02/ruby-procs-and-lambdas/) is inline or multiline. For example,

```ruby
# inline block (joined)
some_list.each { |x| puts x }

# multiline block (split)
some_list.each do |x|
  puts x
end
```

It does not look like the [ruby](https://github.com/Wansmer/treesj/blob/main/lua/treesj/langs/ruby.lua) treesj preset supports the `block` (or `do_block`) node type as of right now. I would love to see this added as a feature and would be happy to create a PR.

From what I can tell - and correct me if I'm wrong - there are two limitations that are blocking this kind feature:

1. There appears to be a [limitation](https://github.com/Wansmer/treesj/blob/main/lua/treesj/langs/default_preset.lua#L17-L19) on `non_bracketed_node` where the "split" and "join" node representations _must_ use the same syntax. In this case, support for individual bracketed nodes would need to be supported
    ```lua
    -- boolean: Non-bracket nodes (e.g., with then end instead of {}|<>|[])
    -- NOTE: Must be same for both modes
    non_bracket_node = false,
    ```
1. Another limitation (which goes hand-in-hand with the first) is that there are no preset options for defining node replacement. I.e. `do` replaces `{` and `end` replaces `}`

This plugin has some great improvements over splitjoin.vim, hoping to see it continuously improve 🙂 

Happy to hear your thoughts!

**Comment by cbochs** [comment]
Also, here is a snippet of code and its corresponding treesitter representation:

_Code_
```ruby
x.each { |y| puts y }

x.each do |y|
  puts y
end
```

_Treesitter_
```lisp
call [0, 0] - [0, 21]
  receiver: identifier [0, 0] - [0, 1]
  operator: "." [0, 1] - [0, 2]
  method: identifier [0, 2] - [0, 6]
  block: block [0, 7] - [0, 21]
    "{" [0, 7] - [0, 8]
    parameters: block_parameters [0, 9] - [0, 12]
      "|" [0, 9] - [0, 10]
      identifier [0, 10] - [0, 11]
      "|" [0, 11] - [0, 12]
    body: block_body [0, 13] - [0, 19]
      call [0, 13] - [0, 19]
        method: identifier [0, 13] - [0, 17]
        arguments: argument_list [0, 18] - [0, 19]
          identifier [0, 18] - [0, 19]
    "}" [0, 20] - [0, 21]
call [2, 0] - [4, 3]
  receiver: identifier [2, 0] - [2, 1]
  operator: "." [2, 1] - [2, 2]
  method: identifier [2, 2] - [2, 6]
  block: do_block [2, 7] - [4, 3]
    "do" [2, 7] - [2, 9]
    parameters: block_parameters [2, 10] - [2, 13]
      "|" [2, 10] - [2, 11]
      identifier [2, 11] - [2, 12]
      "|" [2, 12] - [2, 13]
    body: body_statement [3, 2] - [3, 8]
      call [3, 2] - [3, 8]
        method: identifier [3, 2] - [3, 6]
        arguments: argument_list [3, 7] - [3, 8]
          identifier [3, 7] - [3, 8]
    "end" [4, 0] - [4, 3]
```

**Comment by Wansmer** [comment]
I'm planning to implement `foreach` option which will execute callback for each node. It'll allow transforming text and change brackets to `do` or `end`, e.t.c.

I think, this features will solve this case

**Comment by cbochs** [comment]
Awesome! Looking forward to it.

**Comment by Wansmer** [comment]
I created draft PR (#68) what can handle `block` and `do_block`. Can you add more examples with same case, please?
If you know examples no only on ruby – it will be excellent.

**Comment by cbochs** [comment]
One more ruby example:

_Block without arguments_
```ruby
# Joined
10.times { puts "foo" }

# Split
10.times do
  puts "foo"
end
```

As for other languages, the only similar constructs I can think of are single-line vs. multi-line strings. For example:

```python
# Joined
some_string = "I am\na\nmultiline\nstring"

# Split
some_string = """
I am
a
multiline
string
"""
```

**Comment by cbochs** [comment]
@Wansmer I found a case that appears to be incorrectly splitting:

_Code (Ruby)_
```ruby
# Original
let(:some_array) do
  [
    { bar: "bar" }
  ]
end

# Joined
let(:some_array) { [ { bar: "bar" } ] }

# Split again
let(:some_array) do
  [ { bar: "bar" } ]
end
```

**Expected**: split should be reversible and not change the inner array (`[]`)

**Comment by Wansmer** [comment]
> @Wansmer I found a case that appears to be incorrectly splitting:

It is not incorrectly: `recursive` is false by [default](https://github.com/Wansmer/treesj#nodes-configuration) for `split`.
It can be activated with:
```lua
  block = u.set_preset_for_dict({
    split = {
      recursive = true,
      recursive_ignore = { 'hash' }, -- not splitting hash
    },
  }),
```

**Comment by Wansmer** [comment]
Done in #68

**Comment by cbochs** [comment]
This works fantastic. Thanks you!
