### ISSUE TITLE
List the default keymaps in the readme

### ISSUE THREAD

**Issue by s1n7ax** [Wansmer/treesj#7]
I can see a config called `use_default_keymaps` but there is no information about what the default keymaps are.

**Comment by Wansmer** [comment]
Default keymaps shown at '[Configuration](https://github.com/Wansmer/treesj#plugin-configuration)' section in the readme.

```lua
tsj.setup({
  -- Use default keymaps
  -- (<space>m - toggle, <space>j - join, <space>s - split)
  use_default_keymaps = true,
  -- ...
})
```
