### ISSUE TITLE
Ruby module/namespace joins

### ISSUE THREAD

**Issue by iovis** [Wansmer/treesj#81]
Ruby has some syntactic sugar with namespaces. In particular modules (and classes) can be nested within modules, like so:

```rb
module MyModule
  class MyClass
  end
end

# is the same as
class MyModule::MyClass
end
```

Some examples taken from [splitjoin.vim](https://github.com/AndrewRadev/splitjoin.vim/blob/main/spec/plugin/ruby_spec.rb) would be:

```rb
# RESULT OF JOIN
class Foo::Bar::Baz < Quux
  def initialize
    # foo
  end
end

# RESULT OF SPLIT
module Foo
  module Bar
    class Baz < Quux
      def initialize
        # foo
      end
    end
  end
end

# RESULT OF JOIN
class Foo::Bar::Baz < Quux
end

# RESULT OF SPLIT
module Foo
  module Bar
    class Baz < Quux
    end
  end
end


# RESULT OF JOIN
module A::B
end

# RESULT OF SPLIT
module A
  module B
  end
end


# EXAMPLE WITH MIXED 
module Foo::Bar
  class Baz::Qux
  end
end

# RESULT OF JOIN
class Foo::Bar::Baz::Qux
end
```

This one may be tricky to implement given that they may join into a `class` or a `module` (depending on whether the nested object is one or the other)

**Comment by Wansmer** [comment]
I looked at the examples and their tree-sitter parsing trees.
Unfortunately, at the moment, this is not feasible with TreeSJ.
The difficulty is that you need to change the node at the beginning and at the end, but leave everything in the middle unchanged. 
This is not a join/split in its usual sense, where the join is always single line, and the split is always multiline.
I won't close the issue, and I will think about how to implement this functionality in the next updates.
Thanks for the examples!

**Comment by iovis** [comment]
I was afraid that would be the case, but thank you for looking into it!

**Comment by Wansmer** [comment]
@iovis In #125, the `fallback` option is implemented: in it you can pass control to `splitjoin.vim`. Example: https://github.com/Wansmer/treesj#option-fallback (see `example of usage`).

I'm closing the issue, because processing of such nodes will not be implemented in the near future.

Hope the new option helps.

**Comment by iovis** [comment]
Working beautifully (other than `splitjoin.vim` starting to behave weird with some of these in my codebase haha), I appreciate the new API!
