### ISSUE TITLE
Don't use backslash in Python

### ISSUE THREAD

**Issue by anatoly-kor** [Wansmer/treesj#86]
Hi! How configure plugin for never using backslash in Python(imports, etc)? 
For example:
```python
from airflow.providers.apache.spark.operators.spark_submit import \
    SparkSubmitOperator
```

Prefer:
```python
from airflow.providers.apache.spark.operators.spark_submit import (
    SparkSubmitOperator
)
```

**Comment by Wansmer** [comment]
Hi! TreeSJ by default not using backslash anywhere.

Maybe it results of your formatter utils?


https://user-images.githubusercontent.com/46977173/226286943-ca898bc2-63d4-4175-8aae-9f10cde1b99f.mov

**Comment by anatoly-kor** [comment]
Yea, you are right. It was isort formatter. Thank you!
