### ISSUE TITLE
Splitting not properly formatted for longhand PHP array syntax

### ISSUE THREAD

**Issue by danielpost** [Wansmer/treesj#87]
First of all, thank you for this awesome plugin!

PHP supports creating arrays with both `array()` and `[]. For example, this is a common array structure in PHP:

```php
array( 'one', 'two' )
```

When splitting, this is what I would expect to happen:

```php
array(
  'one',
  'two'
)
```

However, for some reason the array notation gets split up and this happens instead:

```php
array
  (
  'one',
  'two'
)
```

Any idea how I might be able to fix this in my config? Thanks!

**Comment by Wansmer** [comment]
Hi! 
I think, this can be help:
```lua
  array_creation_expression = lang_utils.set_preset_for_dict({
    both = {
      omit = { '(' },
    },
    join = {
      space_in_brackets = true,
    },
  }),
```

**Comment by danielpost** [comment]
@Wansmer That works perfectly, thank you so much for the quick reply and fix! 🎉
