### ISSUE TITLE
Add an option to add trailing comma during split

### ISSUE THREAD

**Issue by alphatroya** [Wansmer/treesj#9]
For Go language a trailing comma is required when items place each on the own line, for example

```go
func a(b int, c int, d int)

func a(
 b int,
 c int,
 d int, // <-comma here is required
)
``` 
The same applied for arrays and dictionaries.

Can't find an option for this, can you point on it if I miss?

**Comment by Wansmer** [comment]
Yes, you can configure it. Option 'last_separator' - https://github.com/Wansmer/treesj#nodes-configuration
