### ISSUE TITLE
Join/Split a chain of method calls

### ISSUE THREAD

**Issue by cagdassalur** [Wansmer/treesj#90]
Would it be possible split/join a chain of method calls?

### Ruby example

```ruby
# from:
all_names = some_object.associations.map{ |o| o.name }.join(',').downcase

# to:
all_names = some_object
  .associations
  .map{ |o| o.name }
  .join(',')
  .downcase
```

_Note: I just installed this plugin and it works amazing, and so fast! Thanks for all the work <3_

**Comment by Wansmer** [comment]
> Note: I just installed this plugin and it works amazing, and so fast! Thanks for all the work <3

Thanks for the feedback!

> Would it be possible split/join a chain of method calls?

Technically, this can be done using the `TreeSJ:format_tree()` or `TreeSJ: format_resulted_lines()` methods. But the tree for such a construct is very convoluted, so I don't think a treesitter solution would be any better here than a regex solution.

**Comment by cagdassalur** [comment]
Ah, too bad. I was hoping to use the same keymapping for this case as well. I have no idea how treesitter works but i'll tinker with it some time to see how it would be done.
Doesn't need to be better than a regex solution but being able to use the same command for splitting arguments would be invaluable.

So closing the ticket, thanks for the answer!

**Comment by bew** [comment]
Keymapping doesn't have to be for a single plugin, you can bind the key to your own function that will call treesj or another as you need!

**Comment by cagdassalur** [comment]
yeah, my wording was bad. I meant having one key to utilize treesj deciding  in a smart way on what to do, autodetection and stuff like that.
