### ISSUE TITLE
Lag on space keypress even when default keybindings are not in use

### ISSUE THREAD

**Issue by sathishmanohar** [Wansmer/treesj#97]
I use the space key to enter the command mode with `nmap <space> :` in my vim config

So I've disabled treesj's default mappings with `use_default_keymaps = false,` in favor of my custom mappings but there is still a noticeable delay of half a second to a second while using the spacebar.

**Comment by Wansmer** [comment]
Why you decided what delay comes from TreeSJ? Did you check `:nmap <space>`?

**Comment by sathishmanohar** [comment]
It only showed up when treesj was installed and enabled. Strangely, Now I have the treesj enabled but there is no delay now.

**Comment by Wansmer** [comment]
> It only showed up when treesj was installed and enabled. Strangely, Now I have the treesj enabled but there is no delay now.

Great! Then I am closing an issue.
